name: test-and-publish

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-18.04, windows-2019]
        include:
          - environment: ubuntu-18.04
            publish-runtime-id: linux-x64
          - environment: windows-2019
            publish-runtime-id: win10-x64

    runs-on: ${{ matrix.environment }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.402'
    - name: Try use dotnet core 3
      run: dotnet --info
    - uses: actions/checkout@v1

    - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
      run: dotnet clean ./implement/test-elm-fullstack/test-elm-fullstack.csproj && dotnet nuget locals all --clear

    - name: dotnet publish
      env:
        PUBLISH_RUNTIME_ID: ${{ matrix.publish-runtime-id }}
      run: dotnet publish -c Debug --runtime ${{ env.PUBLISH_RUNTIME_ID }} --self-contained true /p:PublishReadyToRun=true /p:PublishSingleFile=true ./implement/elm-fullstack
    - name: Publish artifacts
      uses: actions/upload-artifact@v1
      with:
        name: elm-fullstack-bin-${{github.sha}}-${{ matrix.publish-runtime-id }}
        path: ./implement/elm-fullstack/bin/Debug/netcoreapp3.1/${{ matrix.publish-runtime-id }}/publish
    - name: dotnet publish with separate assemblies
      run: dotnet publish -c Debug ./implement/elm-fullstack --output ./publish-separate-assemblies
    - name: Publish artifacts with separate assemblies
      uses: actions/upload-artifact@v1
      with:
        name: elm-fullstack-separate-assemblies-${{github.sha}}-${{ matrix.publish-runtime-id }}
        path: ./publish-separate-assemblies
